### ISSUE TITLE
why Yolov10 only support wasm ? 

### ISSUE THREAD

**Issue by chopin1998** [nomi30701/yolo-model-benchmark-onnxruntime-web#2]
newbie to this, please help

**Comment by chopin1998** [comment]
i see some error like those

> ort-wasm-simd.jsep.wasm:0xf3e0f7 2024-08-09 16:13:04.545300 [E:onnxruntime:, sequential_executor.cc:516 ExecuteKernel] Non-zero status code returned while running Softmax node. Name:'/model.22/dfl/Softmax' Status Message: Failed to run JSEP kernel


how to convert a onnx model match webGPU?

**Comment by chopin1998** [comment]
i got the solution! thank you!

**Comment by nomi30701** [comment]
@chopin1998 I change onnx model opset=12 in yolov10, it work for WebGPU.
